apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
  labels:
    component: mutating-controller
webhooks:
  - name: test.example.com
    failurePolicy: Fail
    clientConfig:
      service:
        name: test-mutations
        namespace: default
        path: /mutate/deployments
        port: 8001
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVEekNDQXZlZ0F3SUJBZ0lVWDU0NjdwYkhJSmRGd1hqUlVzdE1JaWRzV1NBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daWXhDekFKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKRFFURVJNQThHQTFVRUJ3d0lVMkZ1SUVwdgpjMlV4RFRBTEJnTlZCQW9NQkhSbGMzUXhEVEFMQmdOVkJBc01CSFJsYzNReEl6QWhCZ05WQkFNTUduUmxjM1F0CmJYVjBZWFJwYjI1ekxtUmxabUYxYkhRdWMzWmpNU1F3SWdZSktvWklodmNOQVFrQkZoVnVhV3htY21GdVFHMXAKWTNKdmMyOW1kQzVqYjIwd0hoY05NakF4TVRBMk1qSTFNREF3V2hjTk1qTXdPREkzTWpJMU1EQXdXakNCbGpFTApNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1SRXdEd1lEVlFRSERBaFRZVzRnU205elpURU5NQXNHCkExVUVDZ3dFZEdWemRERU5NQXNHQTFVRUN3d0VkR1Z6ZERFak1DRUdBMVVFQXd3YWRHVnpkQzF0ZFhSaGRHbHYKYm5NdVpHVm1ZWFZzZEM1emRtTXhKREFpQmdrcWhraUc5dzBCQ1FFV0ZXNXBiR1p5WVc1QWJXbGpjbTl6YjJaMApMbU52YlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTFabWYzQmRLeVZBVXVQCnoyRyt0d1NyTXhPSSs4NzRYT1Z0dUpNWTJYeExwcHRKaU5tODlicGMwcmZEWUt0U3ZWUjBYZ1F3eTFOOTQ2ZlcKZW54TDIzRDVjRXZteVVWazhYaDQvYmtBMnlzZUxmeGhNOU9oUU5mNzJhaXYvbkZhdytCeU1yZTZNaFBGZGptNgpTOWNOODMzMWJRcHQzaHh4RlczOTVhZFdBRFBncVZIbGJ1R3VaS2hOUGlVRm5NYm1XSXNLOHFLeFU1U3VteUtnCndmNzdEcndYY3hjMWdMdE1YNHdtUmQveDE1NXY3Z1pkRlpkaGNtRWFGVXV2WUZ5M2Z3V0I5bXhjU2xpZjFKQXcKRkhIOUY5SnlzS3dWQlNuaC9PNlRQY2V2cjVRSDZDVUVxdG5NZEFidzIrMnZFN2N4Sy9kcnp1Z1daSU1HSXhuUApncEFJS1BFQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZINjJ4ZXdPM25rRGZJaTlzc2hCYm1FRDdQOTVNQjhHCkExVWRJd1FZTUJhQUZINjJ4ZXdPM25rRGZJaTlzc2hCYm1FRDdQOTVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUZVaXRhMzFKcjJSTW8wZWFmVnJDUzVEWmc1UGE2UHQ4T0svQVpqMgp6dkwzNDNEdU5lTklKQUc0eFU2T0tJUk96ZmF4Q251dWl2eWZRa2dEODErbXRFMWpDYkVUWmY3Zkx0MThVL0JoCk9qbkJ6REcra0loNER1ZG0rVFU2azZHQStSYVlNaFF4bXdEMHA3Y3l3WlpjTnF5aFRBb1E3QS9ROGE4d3V4Y3MKTFc4c0Q2VWlyaDVyTGYyOUEzS3JZQVB3ZDdPOFV2ajhicGRYTTdycXhmRjZqZEJCc0RYN2RCSFAyTXhGYWpjMwpoOWh5Tm14VjZUbGlLUStYeFQ3TXRadDMvSExiOVEraWlGU2lNNXdHZ3FXdDd1TW5jcjFOeTlQaWhiOWRWbVhjClNiSENGNm5QUDgzSnZVcGVhSkRTdURHeDBINzIyK25NVzNhcUh1WmVOa1ZxZGhnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - apiGroups: ["apps"]
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE